---
title: "Project proposal"
output: github_document
---

# Project Tentative Title: Mental Health Post Covid Pandemic 

**Members: Fei Xiao(fx2184), Kelly Luo(sl5012), Tongtong Zhu(tz2520), Yi Fang(yf2605), Yujie Huang(yh3429)** 


## Motivation
Mental health is an important part of overall health and well-being. Mental health includes our emotional, psychological, and social well-being. It affects how we think, feel, and act. It also helps determine how we handle stress, relate to others, and make healthy choices. Mental health is essential from childhood and adolescence through adulthood.  

The impact of Covid-19 on mental illnesses like depression and anxiety are still under investigation. The CDC reports that mental illness can increase the risk of diabetes, stroke and heart disease and has recognized that severe mental illness can increase the likelihood of a person becoming seriously ill after contracting COVID-19.


## Intended final products
The final product will be a website that includes data summaries, visualizations, a screencast, written report and corresponding github repository containing all relevant program files and outputs related to the project. The website is open for public audiences and aims to engage with the public, especially for people who are suffering from or interested in mental health problems. Also, we expect our website could help people maintain mental health and wellness. 


## anticipated data sources
https://www.cdc.gov/nchs/nhis/2020nhis.htm 
The National Health Interview Survey (NHIS) is the principal source of information on the health of the civilian noninstitutionalized population of the United States and is one of the major data collection programs of the National Center for Health Statistics (NCHS) which is part of the Centers for Disease Control and Prevention (CDC). Mental health data can be readily available through the CDC official website. These data span from 2004 to 2019 and include descriptive information related to mental health status, and people social behaviors during pandemic and so on. These data are at the individual level.

https://healthsurveys.ipums.org
Data nhis_0002.dat was downloaded from IPUMS Health Surveys, which provide free individual-level survey data for research purposes from two leading sources of self-reported health and health care access information: the National Health Interview Survey (NHIS) and the Medical Expenditure Panel Survey (MEPS). For now, our data contains anxiety level and other SES information from 2018 to 2021, and includs individuals’ age, sex , education level, number of person in family, medication status for anxious feelings, etc. 


## planned analyses / visualizations / coding challenges
- Quiz format liked to answer pages with data and visualization to justify the answers and additional resources.

- Investigating variables that have significant effects on mental health, such as income, number of people living with, number of pets. 

- Descriptive and inferential statistical analyses for mental health and potential related factors.

- Visualizations to show how different risk factors' effect on different mental health problems changes before and after pandemic.


## planned timeline
- Nov 13-Nov 25:Data preparation and exploratory analysis
- Nov 26: Decide final visualization and tables
- Nov 27-Dec 3: Project description and video 
- Dec 3-Dec 9: Web pages and adjustment
- Dec10: Final check, Submission and Peer assessment

